//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class bom : XPLiteObject
    {
        int fitem_id;
        [Key]
        public int item_id
        {
            get { return fitem_id; }
            set { SetPropertyValue<int>(nameof(item_id), ref fitem_id, value); }
        }
        int fparent_id;
        public int parent_id
        {
            get { return fparent_id; }
            set { SetPropertyValue<int>(nameof(parent_id), ref fparent_id, value); }
        }
        string fitem_name;
        [Size(20)]
        public string item_name
        {
            get { return fitem_name; }
            set { SetPropertyValue<string>(nameof(item_name), ref fitem_name, value); }
        }
        int fitem_qty;
        public int item_qty
        {
            get { return fitem_qty; }
            set { SetPropertyValue<int>(nameof(item_qty), ref fitem_qty, value); }
        }
    }

}
