//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class cod03m00 : XPLiteObject
    {
        long fmngr_cd;
        [Key]
        public long mngr_cd
        {
            get { return fmngr_cd; }
            set { SetPropertyValue<long>(nameof(mngr_cd), ref fmngr_cd, value); }
        }
        long fp_mngr_cd;
        public long p_mngr_cd
        {
            get { return fp_mngr_cd; }
            set { SetPropertyValue<long>(nameof(p_mngr_cd), ref fp_mngr_cd, value); }
        }
        long fseq;
        [ColumnDbDefaultValue("0")]
        public long seq
        {
            get { return fseq; }
            set { SetPropertyValue<long>(nameof(seq), ref fseq, value); }
        }
    }

}
