//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class cod02t20 : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Size(10)]
            [Persistent("tree_id")]
            public string tree_id { get; set; }
            [Size(10)]
            [Persistent("tree_p_id")]
            public string tree_p_id { get; set; }
            [Size(5)]
            [Persistent("mngr_cd")]
            public string mngr_cd { get; set; }
            [Size(5)]
            [Persistent("cd")]
            public string cd { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
