//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class cod02t00 : XPLiteObject
    {
        string fmngr_tp_nm;
        [Size(200)]
        public string mngr_tp_nm
        {
            get { return fmngr_tp_nm; }
            set { SetPropertyValue<string>(nameof(mngr_tp_nm), ref fmngr_tp_nm, value); }
        }
        char fuse_yn;
        [ColumnDbDefaultValue("'Y'::bpchar")]
        public char use_yn
        {
            get { return fuse_yn; }
            set { SetPropertyValue<char>(nameof(use_yn), ref fuse_yn, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("mngr_gb")]
            public long mngr_gb { get; set; }
            [Persistent("mngr_tp")]
            public long mngr_tp { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
