//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class cod02m00 : XPLiteObject
    {
        long fmngr_gb;
        [Key]
        [ColumnDbDefaultValue("0")]
        public long mngr_gb
        {
            get { return fmngr_gb; }
            set { SetPropertyValue<long>(nameof(mngr_gb), ref fmngr_gb, value); }
        }
        string fmngr_gb_nm;
        [Size(200)]
        public string mngr_gb_nm
        {
            get { return fmngr_gb_nm; }
            set { SetPropertyValue<string>(nameof(mngr_gb_nm), ref fmngr_gb_nm, value); }
        }
        char fuse_yn;
        [ColumnDbDefaultValue("'Y'::bpchar")]
        public char use_yn
        {
            get { return fuse_yn; }
            set { SetPropertyValue<char>(nameof(use_yn), ref fuse_yn, value); }
        }
    }

}
