//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class cod02t10 : XPLiteObject
    {
        string fmngr_cd_nm;
        [Size(200)]
        public string mngr_cd_nm
        {
            get { return fmngr_cd_nm; }
            set { SetPropertyValue<string>(nameof(mngr_cd_nm), ref fmngr_cd_nm, value); }
        }
        string funit_tp;
        [Size(10)]
        public string unit_tp
        {
            get { return funit_tp; }
            set { SetPropertyValue<string>(nameof(unit_tp), ref funit_tp, value); }
        }
        decimal funit;
        [ColumnDbDefaultValue("0")]
        public decimal unit
        {
            get { return funit; }
            set { SetPropertyValue<decimal>(nameof(unit), ref funit, value); }
        }
        char fuse_yn;
        [ColumnDbDefaultValue("'Y'::bpchar")]
        public char use_yn
        {
            get { return fuse_yn; }
            set { SetPropertyValue<char>(nameof(use_yn), ref fuse_yn, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("mngr_gb")]
            public long mngr_gb { get; set; }
            [Persistent("mngr_tp")]
            public long mngr_tp { get; set; }
            [Persistent("mngr_cd")]
            public long mngr_cd { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
