//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class file01m00 : XPLiteObject
    {
        string fdescription;
        [Size(200)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        byte[] ffile;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] file
        {
            get { return ffile; }
            set { SetPropertyValue<byte[]>(nameof(file), ref ffile, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(50)]
            [Persistent("file_name")]
            public string file_name { get; set; }
            [Size(8)]
            [Persistent("work_date")]
            public string work_date { get; set; }
            [Size(8)]
            [Persistent("work_user")]
            public string work_user { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
