//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class item01m00 : XPLiteObject
    {
        char fnode_tp;
        public char node_tp
        {
            get { return fnode_tp; }
            set { SetPropertyValue<char>(nameof(node_tp), ref fnode_tp, value); }
        }
        long fparent_order_seq;
        public long parent_order_seq
        {
            get { return fparent_order_seq; }
            set { SetPropertyValue<long>(nameof(parent_order_seq), ref fparent_order_seq, value); }
        }
        long fkey_order_seq;
        public long key_order_seq
        {
            get { return fkey_order_seq; }
            set { SetPropertyValue<long>(nameof(key_order_seq), ref fkey_order_seq, value); }
        }
        string fitem_name;
        [Size(200)]
        public string item_name
        {
            get { return fitem_name; }
            set { SetPropertyValue<string>(nameof(item_name), ref fitem_name, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("parent")]
            public long parent { get; set; }
            [Persistent("item_key")]
            public long item_key { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
