//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class pipetool_tree : XPLiteObject
    {
        long fnext_id;
        public long next_id
        {
            get { return fnext_id; }
            set { SetPropertyValue<long>(nameof(next_id), ref fnext_id, value); }
        }
        long fsheet_index;
        public long sheet_index
        {
            get { return fsheet_index; }
            set { SetPropertyValue<long>(nameof(sheet_index), ref fsheet_index, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(10)]
            [Persistent("project_cd")]
            public string project_cd { get; set; }
            [Persistent("id")]
            public long id { get; set; }
            [Size(30)]
            [Persistent("line_info")]
            public string line_info { get; set; }
            [Size(20)]
            [Persistent("sheet_info")]
            public string sheet_info { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
