//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class pipetool_line : XPLiteObject
    {
        char fmanhole_tp;
        public char manhole_tp
        {
            get { return fmanhole_tp; }
            set { SetPropertyValue<char>(nameof(manhole_tp), ref fmanhole_tp, value); }
        }
        decimal fdist2;
        public decimal dist2
        {
            get { return fdist2; }
            set { SetPropertyValue<decimal>(nameof(dist2), ref fdist2, value); }
        }
        decimal fgh;
        public decimal gh
        {
            get { return fgh; }
            set { SetPropertyValue<decimal>(nameof(gh), ref fgh, value); }
        }
        decimal finv;
        public decimal inv
        {
            get { return finv; }
            set { SetPropertyValue<decimal>(nameof(inv), ref finv, value); }
        }
        decimal fdia;
        public decimal dia
        {
            get { return fdia; }
            set { SetPropertyValue<decimal>(nameof(dia), ref fdia, value); }
        }
        string flinename;
        [Size(19)]
        public string linename
        {
            get { return flinename; }
            set { SetPropertyValue<string>(nameof(linename), ref flinename, value); }
        }
        string fpavement_type;
        [Size(10)]
        public string pavement_type
        {
            get { return fpavement_type; }
            set { SetPropertyValue<string>(nameof(pavement_type), ref fpavement_type, value); }
        }
        decimal fslope;
        public decimal slope
        {
            get { return fslope; }
            set { SetPropertyValue<decimal>(nameof(slope), ref fslope, value); }
        }
        long fsheet_index;
        public long sheet_index
        {
            get { return fsheet_index; }
            set { SetPropertyValue<long>(nameof(sheet_index), ref fsheet_index, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(10)]
            [Persistent("project_cd")]
            public string project_cd { get; set; }
            [Persistent("id")]
            public long id { get; set; }
            [Size(30)]
            [Persistent("line_info")]
            public string line_info { get; set; }
            [Size(20)]
            [Persistent("sheet_info")]
            public string sheet_info { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
