//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class plh01m00 : XPLiteObject
    {
        string flinenumber;
        [Size(20)]
        public string linenumber
        {
            get { return flinenumber; }
            set { SetPropertyValue<string>(nameof(linenumber), ref flinenumber, value); }
        }
        string fextention;
        [Size(20)]
        [ColumnDbDefaultValue("NULL::bpchar")]
        public string extention
        {
            get { return fextention; }
            set { SetPropertyValue<string>(nameof(extention), ref fextention, value); }
        }
        decimal fdist;
        public decimal dist
        {
            get { return fdist; }
            set { SetPropertyValue<decimal>(nameof(dist), ref fdist, value); }
        }
        decimal fdist2;
        public decimal dist2
        {
            get { return fdist2; }
            set { SetPropertyValue<decimal>(nameof(dist2), ref fdist2, value); }
        }
        decimal fgh;
        public decimal gh
        {
            get { return fgh; }
            set { SetPropertyValue<decimal>(nameof(gh), ref fgh, value); }
        }
        decimal finv;
        public decimal inv
        {
            get { return finv; }
            set { SetPropertyValue<decimal>(nameof(inv), ref finv, value); }
        }
        string flinename;
        [Size(19)]
        [ColumnDbDefaultValue("NULL::bpchar")]
        public string linename
        {
            get { return flinename; }
            set { SetPropertyValue<string>(nameof(linename), ref flinename, value); }
        }
        decimal fdia;
        public decimal dia
        {
            get { return fdia; }
            set { SetPropertyValue<decimal>(nameof(dia), ref fdia, value); }
        }
        decimal fbr;
        public decimal br
        {
            get { return fbr; }
            set { SetPropertyValue<decimal>(nameof(br), ref fbr, value); }
        }
        decimal ftype;
        public decimal type
        {
            get { return ftype; }
            set { SetPropertyValue<decimal>(nameof(type), ref ftype, value); }
        }
        decimal ft1;
        public decimal t1
        {
            get { return ft1; }
            set { SetPropertyValue<decimal>(nameof(t1), ref ft1, value); }
        }
        decimal fslope;
        public decimal slope
        {
            get { return fslope; }
            set { SetPropertyValue<decimal>(nameof(slope), ref fslope, value); }
        }
        decimal fbcut;
        public decimal bcut
        {
            get { return fbcut; }
            set { SetPropertyValue<decimal>(nameof(bcut), ref fbcut, value); }
        }
        decimal fhcut;
        public decimal hcut
        {
            get { return fhcut; }
            set { SetPropertyValue<decimal>(nameof(hcut), ref fhcut, value); }
        }
        decimal fmanwork;
        public decimal manwork
        {
            get { return fmanwork; }
            set { SetPropertyValue<decimal>(nameof(manwork), ref fmanwork, value); }
        }
        decimal fsand;
        public decimal sand
        {
            get { return fsand; }
            set { SetPropertyValue<decimal>(nameof(sand), ref fsand, value); }
        }
        decimal fbaseangle;
        public decimal baseangle
        {
            get { return fbaseangle; }
            set { SetPropertyValue<decimal>(nameof(baseangle), ref fbaseangle, value); }
        }
        decimal fconca;
        public decimal conca
        {
            get { return fconca; }
            set { SetPropertyValue<decimal>(nameof(conca), ref fconca, value); }
        }
        decimal fconcb;
        public decimal concb
        {
            get { return fconcb; }
            set { SetPropertyValue<decimal>(nameof(concb), ref fconcb, value); }
        }
        decimal fhumanity;
        public decimal humanity
        {
            get { return fhumanity; }
            set { SetPropertyValue<decimal>(nameof(humanity), ref fhumanity, value); }
        }
        decimal fconcrete;
        public decimal concrete
        {
            get { return fconcrete; }
            set { SetPropertyValue<decimal>(nameof(concrete), ref fconcrete, value); }
        }
        decimal fasphalt1;
        public decimal asphalt1
        {
            get { return fasphalt1; }
            set { SetPropertyValue<decimal>(nameof(asphalt1), ref fasphalt1, value); }
        }
        decimal fasphalt2;
        public decimal asphalt2
        {
            get { return fasphalt2; }
            set { SetPropertyValue<decimal>(nameof(asphalt2), ref fasphalt2, value); }
        }
        decimal fcomplay;
        public decimal complay
        {
            get { return fcomplay; }
            set { SetPropertyValue<decimal>(nameof(complay), ref fcomplay, value); }
        }
        decimal fmixlay;
        public decimal mixlay
        {
            get { return fmixlay; }
            set { SetPropertyValue<decimal>(nameof(mixlay), ref fmixlay, value); }
        }
        decimal fmixlay1;
        public decimal mixlay1
        {
            get { return fmixlay1; }
            set { SetPropertyValue<decimal>(nameof(mixlay1), ref fmixlay1, value); }
        }
        decimal fmixlay2;
        public decimal mixlay2
        {
            get { return fmixlay2; }
            set { SetPropertyValue<decimal>(nameof(mixlay2), ref fmixlay2, value); }
        }
        decimal farea1;
        public decimal area1
        {
            get { return farea1; }
            set { SetPropertyValue<decimal>(nameof(area1), ref farea1, value); }
        }
        decimal farea2;
        public decimal area2
        {
            get { return farea2; }
            set { SetPropertyValue<decimal>(nameof(area2), ref farea2, value); }
        }
        decimal farea3;
        public decimal area3
        {
            get { return farea3; }
            set { SetPropertyValue<decimal>(nameof(area3), ref farea3, value); }
        }
        decimal farea4;
        public decimal area4
        {
            get { return farea4; }
            set { SetPropertyValue<decimal>(nameof(area4), ref farea4, value); }
        }
        decimal farea5;
        public decimal area5
        {
            get { return farea5; }
            set { SetPropertyValue<decimal>(nameof(area5), ref farea5, value); }
        }
        decimal farea6;
        public decimal area6
        {
            get { return farea6; }
            set { SetPropertyValue<decimal>(nameof(area6), ref farea6, value); }
        }
        decimal farea7;
        public decimal area7
        {
            get { return farea7; }
            set { SetPropertyValue<decimal>(nameof(area7), ref farea7, value); }
        }
        decimal farea8;
        public decimal area8
        {
            get { return farea8; }
            set { SetPropertyValue<decimal>(nameof(area8), ref farea8, value); }
        }
        decimal farea9;
        public decimal area9
        {
            get { return farea9; }
            set { SetPropertyValue<decimal>(nameof(area9), ref farea9, value); }
        }
        decimal farea10;
        public decimal area10
        {
            get { return farea10; }
            set { SetPropertyValue<decimal>(nameof(area10), ref farea10, value); }
        }
        decimal farea11;
        public decimal area11
        {
            get { return farea11; }
            set { SetPropertyValue<decimal>(nameof(area11), ref farea11, value); }
        }
        decimal ft2;
        public decimal t2
        {
            get { return ft2; }
            set { SetPropertyValue<decimal>(nameof(t2), ref ft2, value); }
        }
        decimal ft3;
        public decimal t3
        {
            get { return ft3; }
            set { SetPropertyValue<decimal>(nameof(t3), ref ft3, value); }
        }
        decimal ft4;
        public decimal t4
        {
            get { return ft4; }
            set { SetPropertyValue<decimal>(nameof(t4), ref ft4, value); }
        }
        decimal fb;
        public decimal b
        {
            get { return fb; }
            set { SetPropertyValue<decimal>(nameof(b), ref fb, value); }
        }
        decimal fh;
        public decimal h
        {
            get { return fh; }
            set { SetPropertyValue<decimal>(nameof(h), ref fh, value); }
        }
        string fdir;
        [Size(30)]
        [ColumnDbDefaultValue("NULL::bpchar")]
        public string dir
        {
            get { return fdir; }
            set { SetPropertyValue<string>(nameof(dir), ref fdir, value); }
        }
        char fmanhole_yn;
        [ColumnDbDefaultValue("'N'::bpchar")]
        public char manhole_yn
        {
            get { return fmanhole_yn; }
            set { SetPropertyValue<char>(nameof(manhole_yn), ref fmanhole_yn, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(10)]
            [Persistent("project_cd")]
            public string project_cd { get; set; }
            [Persistent("key")]
            public long key { get; set; }
            [Persistent("order_seq")]
            public long order_seq { get; set; }
            [Persistent("filename")]
            public string filename { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
