//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class section01t00 : XPLiteObject
    {
        string fsection_id_nm;
        [Size(255)]
        public string section_id_nm
        {
            get { return fsection_id_nm; }
            set { SetPropertyValue<string>(nameof(section_id_nm), ref fsection_id_nm, value); }
        }
        decimal fasphalt1;
        public decimal asphalt1
        {
            get { return fasphalt1; }
            set { SetPropertyValue<decimal>(nameof(asphalt1), ref fasphalt1, value); }
        }
        decimal fasphalt2;
        public decimal asphalt2
        {
            get { return fasphalt2; }
            set { SetPropertyValue<decimal>(nameof(asphalt2), ref fasphalt2, value); }
        }
        decimal fcomplay;
        public decimal complay
        {
            get { return fcomplay; }
            set { SetPropertyValue<decimal>(nameof(complay), ref fcomplay, value); }
        }
        decimal fmixlay;
        public decimal mixlay
        {
            get { return fmixlay; }
            set { SetPropertyValue<decimal>(nameof(mixlay), ref fmixlay, value); }
        }
        string fdesc;
        [Size(255)]
        public string desc
        {
            get { return fdesc; }
            set { SetPropertyValue<string>(nameof(desc), ref fdesc, value); }
        }
        char fuse_yn;
        [ColumnDbDefaultValue("'Y'::bpchar")]
        public char use_yn
        {
            get { return fuse_yn; }
            set { SetPropertyValue<char>(nameof(use_yn), ref fuse_yn, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(5)]
            [Persistent("section_group_cd")]
            public string section_group_cd { get; set; }
            [Size(5)]
            [Persistent("section_id")]
            public string section_id { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
