//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace xpotest.Tops
{

    public partial class usr01m00 : XPLiteObject
    {
        string fuser_id;
        [Key]
        [Size(8)]
        public string user_id
        {
            get { return fuser_id; }
            set { SetPropertyValue<string>(nameof(user_id), ref fuser_id, value); }
        }
        string fuser_nm;
        [Size(30)]
        public string user_nm
        {
            get { return fuser_nm; }
            set { SetPropertyValue<string>(nameof(user_nm), ref fuser_nm, value); }
        }
        string fmngr_grade;
        [Size(5)]
        public string mngr_grade
        {
            get { return fmngr_grade; }
            set { SetPropertyValue<string>(nameof(mngr_grade), ref fmngr_grade, value); }
        }
        string fhp_no;
        [Size(13)]
        public string hp_no
        {
            get { return fhp_no; }
            set { SetPropertyValue<string>(nameof(hp_no), ref fhp_no, value); }
        }
        string ftel_no;
        [Size(13)]
        public string tel_no
        {
            get { return ftel_no; }
            set { SetPropertyValue<string>(nameof(tel_no), ref ftel_no, value); }
        }
        string foffice_no;
        [Size(13)]
        public string office_no
        {
            get { return foffice_no; }
            set { SetPropertyValue<string>(nameof(office_no), ref foffice_no, value); }
        }
        string fpswd;
        [Size(8)]
        public string pswd
        {
            get { return fpswd; }
            set { SetPropertyValue<string>(nameof(pswd), ref fpswd, value); }
        }
        string fwork_empl;
        [Size(8)]
        public string work_empl
        {
            get { return fwork_empl; }
            set { SetPropertyValue<string>(nameof(work_empl), ref fwork_empl, value); }
        }
        DateTime fwork_dtm;
        public DateTime work_dtm
        {
            get { return fwork_dtm; }
            set { SetPropertyValue<DateTime>(nameof(work_dtm), ref fwork_dtm, value); }
        }
    }

}
